version: 2.2.1.{build}

configuration: Release

assembly_info:
  patch: true
  file: src\SignhostAPIClient\Properties\AssemblyInfo.cs
  assembly_version: '{version}'
  assembly_file_version: '{version}'

before_build:
- cmd: nuget restore "src\SignhostAPIClient.sln

build:
  parallel: true
  project: src\SignhostAPIClient.sln
  publish_nuget: true
  include_nuget_references: true

nuget:
  project_feed: true
  disable_publish_on_pr: false

artifacts:
  - path: '**\SignhostAPIClient*.nupkg'
    name: Nuget

notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/69c5136a745342743ec4
